CREATE TABLE employees
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name     VARCHAR(255) NOT NULL,
    first_name    VARCHAR(255) NOT NULL,
    position      VARCHAR(255) NOT NULL,
    salary        INTEGER      NOT NULL,
    department_id INTEGER,
    FOREIGN KEY (department_id) REFERENCES departments (id)
);

CREATE TABLE departments
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);